import type { GameItem, GameCategory } from "../types/game";

export const animalsCategory: GameCategory = {
  id: "animals.weight",
  question: "Which animal weighs the most?",
  unit: "kg",
  source: {
    name: "Wikipedia (largest animals, species pages)",
    url: "https://en.wikipedia.org/wiki/List_of_largest_organisms",
  },
};

export const animalsItems: GameItem[] = [
  {
    id: "animal-1",
    name: "Blue Whale",
    label: "Weight 150000 kg",
    value: 150000,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-2",
    name: "Sperm Whale",
    label: "Weight 57000 kg",
    value: 57000,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-3",
    name: "Whale Shark",
    label: "Weight 19000 kg",
    value: 19000,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-4",
    name: "Orca",
    label: "Weight 6000 kg",
    value: 6000,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-5",
    name: "African Elephant",
    label: "Weight 6000 kg",
    value: 6000,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-6",
    name: "Hippopotamus",
    label: "Weight 1500 kg",
    value: 1500,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-7",
    name: "Giraffe",
    label: "Weight 1200 kg",
    value: 1200,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-8",
    name: "Great White Shark",
    label: "Weight 1100 kg",
    value: 1100,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-9",
    name: "Bison",
    label: "Weight 900 kg",
    value: 900,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-10",
    name: "Cow",
    label: "Weight 750 kg",
    value: 750,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-11",
    name: "Moose",
    label: "Weight 700 kg",
    value: 700,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-12",
    name: "Polar Bear",
    label: "Weight 650 kg",
    value: 650,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-13",
    name: "Horse",
    label: "Weight 600 kg",
    value: 600,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-14",
    name: "Grizzly Bear",
    label: "Weight 360 kg",
    value: 360,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-15",
    name: "Alligator",
    label: "Weight 230 kg",
    value: 230,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-16",
    name: "Tiger",
    label: "Weight 220 kg",
    value: 220,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-17",
    name: "Sea Lion",
    label: "Weight 200 kg",
    value: 200,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-18",
    name: "Lion",
    label: "Weight 190 kg",
    value: 190,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-19",
    name: "Gorilla",
    label: "Weight 160 kg",
    value: 160,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-20",
    name: "Ostrich",
    label: "Weight 104 kg",
    value: 104,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-21",
    name: "Giant Panda",
    label: "Weight 100 kg",
    value: 100,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-22",
    name: "Human",
    label: "Weight 70 kg",
    value: 70,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-23",
    name: "Kangaroo",
    label: "Weight 60 kg",
    value: 60,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-24",
    name: "Wolf",
    label: "Weight 50 kg",
    value: 50,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-25",
    name: "Cheetah",
    label: "Weight 35 kg",
    value: 35,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-26",
    name: "Swan",
    label: "Weight 12 kg",
    value: 12,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
  {
    id: "animal-27",
    name: "Chicken",
    label: "Weight 1 kg",
    value: 1,
    unit: "kg",
    categoryId: "animals.weight",
    source: { name: "Wikipedia" },
  },
];
