import type { BackendTrack } from "./normalize";

export const mockBackendTracks: BackendTrack[] = [
  {
    _id: "a1",
    trackId: "animal-1",
    trackTitle: "Weight 150000 kg",
    trackArtist: "Blue Whale",
    releaseYear: 150000,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a2",
    trackId: "animal-2",
    trackTitle: "Weight 6000 kg",
    trackArtist: "African Elephant",
    releaseYear: 6000,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a3",
    trackId: "animal-3",
    trackTitle: "Weight 57000 kg",
    trackArtist: "Sperm Whale",
    releaseYear: 57000,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a4",
    trackId: "animal-4",
    trackTitle: "Weight 19000 kg",
    trackArtist: "Whale Shark",
    releaseYear: 19000,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a5",
    trackId: "animal-5",
    trackTitle: "Weight 6000 kg",
    trackArtist: "Orca",
    releaseYear: 6000,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a6",
    trackId: "animal-6",
    trackTitle: "Weight 1500 kg",
    trackArtist: "Hippopotamus",
    releaseYear: 1500,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a7",
    trackId: "animal-7",
    trackTitle: "Weight 1200 kg",
    trackArtist: "Giraffe",
    releaseYear: 1200,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a8",
    trackId: "animal-8",
    trackTitle: "Weight 1100 kg",
    trackArtist: "Great White Shark",
    releaseYear: 1100,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a9",
    trackId: "animal-9",
    trackTitle: "Weight 900 kg",
    trackArtist: "Bison",
    releaseYear: 900,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a10",
    trackId: "animal-10",
    trackTitle: "Weight 750 kg",
    trackArtist: "Cow",
    releaseYear: 750,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a11",
    trackId: "animal-11",
    trackTitle: "Weight 700 kg",
    trackArtist: "Moose",
    releaseYear: 700,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a12",
    trackId: "animal-12",
    trackTitle: "Weight 650 kg",
    trackArtist: "Polar Bear",
    releaseYear: 650,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a13",
    trackId: "animal-13",
    trackTitle: "Weight 600 kg",
    trackArtist: "Horse",
    releaseYear: 600,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a14",
    trackId: "animal-14",
    trackTitle: "Weight 360 kg",
    trackArtist: "Grizzly Bear",
    releaseYear: 360,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a15",
    trackId: "animal-15",
    trackTitle: "Weight 230 kg",
    trackArtist: "Alligator",
    releaseYear: 230,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a16",
    trackId: "animal-16",
    trackTitle: "Weight 220 kg",
    trackArtist: "Tiger",
    releaseYear: 220,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a17",
    trackId: "animal-17",
    trackTitle: "Weight 200 kg",
    trackArtist: "Sea Lion",
    releaseYear: 200,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a18",
    trackId: "animal-18",
    trackTitle: "Weight 190 kg",
    trackArtist: "Lion",
    releaseYear: 190,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a19",
    trackId: "animal-19",
    trackTitle: "Weight 160 kg",
    trackArtist: "Gorilla",
    releaseYear: 160,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a20",
    trackId: "animal-20",
    trackTitle: "Weight 104 kg",
    trackArtist: "Ostrich",
    releaseYear: 104,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a21",
    trackId: "animal-21",
    trackTitle: "Weight 100 kg",
    trackArtist: "Giant Panda",
    releaseYear: 100,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a22",
    trackId: "animal-22",
    trackTitle: "Weight 70 kg",
    trackArtist: "Human",
    releaseYear: 70,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a23",
    trackId: "animal-23",
    trackTitle: "Weight 60 kg",
    trackArtist: "Kangaroo",
    releaseYear: 60,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a24",
    trackId: "animal-24",
    trackTitle: "Weight 50 kg",
    trackArtist: "Wolf",
    releaseYear: 50,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a25",
    trackId: "animal-25",
    trackTitle: "Weight 35 kg",
    trackArtist: "Cheetah",
    releaseYear: 35,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a26",
    trackId: "animal-26",
    trackTitle: "Weight 12 kg",
    trackArtist: "Swan",
    releaseYear: 12,
    trackUrl: "",
    __v: 0,
  },
  {
    _id: "a27",
    trackId: "animal-27",
    trackTitle: "Weight 1 kg",
    trackArtist: "Chicken",
    releaseYear: 1,
    trackUrl: "",
    __v: 0,
  },
];
